name: Terraform Deployment

on: 
  push:
    branches:
      - main

jobs: 
  terraform: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform code
        run: terraform fmt
        
      - name: Plan Terraform changes
        run: terraform plan
        
      - name: Apply Terraform changes
        run: terraform apply -auto-approve  